# Container image that runs your code
FROM alpine:3.10

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/entrypoint.sh"]

# action.yml
name: 'Hello World Docker Action'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: 
    description: 'Who to greet'
    required: true
    default: 'world'
ouputs:
  time:
    description: 'the time we said hello'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}


uses: actions/hello-world-docker-action@main
with:
  who-to-greet: 'Mona the Octocat'
